version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

# Optionally set the version of Python and requirements required to build your docs
python:
  install:
    - requirements: requirements.txt


build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
