name: Mutation Testing CI

on: [push, pull_request]

jobs:
  mutation-test:
    runs-on: ubuntu-latest

    steps:
    - name: 📦 Checkout repository
      uses: actions/checkout@v3

    - name: 🐍 Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: ✅ Add BugsInPy CLI to PATH
      run: echo "$GITHUB_WORKSPACE/BugsInPy/framework/bin" >> $GITHUB_PATH

    - name: 🐍 Confirm Python version
      run: |
        python --version
        which python

    - name: 📥 Install dependencies
      run: |
        pip install -r mutmut/requirements.txt || true
        pip install -e mutmut || true
        pip install python_toolbox
        pip install requests
        pip install PyYAML

    - name: 🌐 Install Ollama CLI
      run: |
        curl -fsSL https://ollama.com/install.sh | sh
        echo "$HOME/.ollama/bin" >> $GITHUB_PATH
        
    - name: 📥 Pull CodeLlama-7b model
      run: ollama pull codellama:7b-instruct

    - name: 🧪 Run diff-based mutation testing on keras bug
      run: |
        python run_bug_test.py

    - name: 📤 Upload mutation results
      uses: actions/upload-artifact@v4
      with:
        name: mutation-results
        path: /tmp/bug-project/**/mutants/survived_mutants.json

    - name: 📥 Move mutant file to expected location
      run: |
        mkdir -p mutants
        cp $(find /tmp/bug-project -name "survived_mutants.json" | head -n 1) mutants/

    - name: 🤖 Run Ollama mutant explainer
      run: |
        python generate_report.py
